version: '3.4'

services:
  appocelot:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    deploy:
     replicas: 1
     restart_policy:
      max_attempts: 3
      condition: on-failure
     placement:
      constraints:
        - node.role == "worker"
  apptwo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:5002"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    deploy:
     replicas: 1
     restart_policy:
      max_attempts: 3
      condition: on-failure
     placement:
      constraints:
        - node.role == "worker"
  appone:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    deploy:
     replicas: 1
     restart_policy:
      max_attempts: 3
      condition: on-failure
     placement:
      constraints:
        - node.role == "worker"
