version: '3.4'

services:
  appocelot:
    image: ${DOCKER_REGISTRY-}appocelot
    build:
      context: .
      dockerfile: App.Ocelot/Dockerfile
    ports:
      - "5000:80" 
    deploy:
     replicas: 1
     restart_policy:
      max_attempts: 1
      condition: on-failure
     placement:
      constraints:
        - node.role == worker
  apptwo:
    image: ${DOCKER_REGISTRY-}apptwo
    build:
      context: .
      dockerfile: AppTwo/Dockerfile
    ports:
      - "5002:5002"
    deploy:
     replicas: 1
     restart_policy:
      max_attempts: 1
      condition: on-failure
     placement:
      constraints:
        - node.role == worker
  appone:
    image: ${DOCKER_REGISTRY-}appone
    build:
      context: .
      dockerfile: AppOne/Dockerfile
    ports:
      - "5001:5001"
    deploy:
     replicas: 1
     restart_policy:
      max_attempts: 1
      condition: on-failure
     placement:
      constraints:
        - node.role == worker
    
    