version: '3.4'

services:
  appocelot:
    image: nginx
    #build:
    #  context: .
    #  dockerfile: App.Ocelot/Dockerfile
    ports:
      - "5000:80" 
    deploy:
      replicas: 1
      restart_policy:
       max_attempts: 1
       condition: on-failure
      placement:
       constraints:
         - node.role == worker
  apptwo:
    image: nginx
    #build:
    #  context: .
    #  dockerfile: AppTwo/Dockerfile
    ports:
      - "5002:80"
    deploy:
      replicas: 1
      restart_policy:
       max_attempts: 1
       condition: on-failure
      placement:
       constraints:
         - node.role == worker
  appone:
    image: nginx
    #build:
    #  context: .
    #  dockerfile: AppOne/Dockerfile
    ports:
      - "5001:80"
    deploy:
      #replicas: 1
      restart_policy:
       max_attempts: 1
       condition: on-failure
      placement:
       constraints:
         - node.role == worker
    
    