version: '3.4'

services:
  appocelot:
    ports:
      - "5000:80"
    deploy:
     replicas: 1
     placement:
      constraints:
       - node.role == worker
  apptwo:
    ports:
      - "5002:5002"
    deploy:
     replicas: 1
     placement:
      constraints:
       - node.role == worker
  appone:
    ports:
      - "5001:5001"
    deploy:
     replicas: 1
     placement:
      constraints:
       - node.role == worker

